function t454_setLogoPadding(recid){if($(window).width()>980){var t454__menu=$('#rec'+recid+' .t454');var t454__logo=t454__menu.find('.t454__logowrapper');var t454__leftpart=t454__menu.find('.t454__leftwrapper');var t454__rightpart=t454__menu.find('.t454__rightwrapper');t454__leftpart.css("padding-right",t454__logo.width()/2+50);t454__rightpart.css("padding-left",t454__logo.width()/2+50)}}
function t454_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t454__list_item a[href='"+url+"']").addClass("t-active");$(".t454__list_item a[href='"+url+"/']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t454_checkAnchorLinks(recid){if($(window).width()>=960){var t454_navLinks=$("#rec"+recid+" .t454__list_item a:not(.tooltipstered)[href*='#']");if(t454_navLinks.length>0){t454_catchScroll(t454_navLinks)}}}
function t454_catchScroll(t454_navLinks){var t454_clickedSectionId=null,t454_sections=new Array(),t454_sectionIdTonavigationLink=[],t454_interval=100,t454_lastCall,t454_timeoutId;t454_navLinks=$(t454_navLinks.get().reverse());t454_navLinks.each(function(){var t454_cursection=t454_getSectionByHref($(this));if(typeof t454_cursection.attr("id")!="undefined"){t454_sections.push(t454_cursection)}
t454_sectionIdTonavigationLink[t454_cursection.attr("id")]=$(this)});t454_updateSectionsOffsets(t454_sections);$(window).bind('resize',t_throttle(function(){t454_updateSectionsOffsets(t454_sections)},200));$('.t454').bind('displayChanged',function(){t454_updateSectionsOffsets(t454_sections)});setInterval(function(){t454_updateSectionsOffsets(t454_sections)},5000);t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId);t454_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t454_navLinks.removeClass('t-active');t454_sectionIdTonavigationLink[t454_getSectionByHref($(this)).attr("id")].addClass('t-active');t454_clickedSectionId=t454_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t454_now=new Date().getTime();if(t454_lastCall&&t454_now<(t454_lastCall+t454_interval)){clearTimeout(t454_timeoutId);t454_timeoutId=setTimeout(function(){t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)},t454_interval-(t454_now-t454_lastCall))}else{t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)}})}
function t454_updateSectionsOffsets(sections){$(sections).each(function(){var t454_curSection=$(this);t454_curSection.attr("data-offset-top",t454_curSection.offset().top)})}
function t454_getSectionByHref(curlink){var t454_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t454_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t454_curLinkValue.substring(1)+"']")}}
function t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId){var t454_scrollPosition=$(window).scrollTop(),t454_valueToReturn=t454_clickedSectionId;if(t454_sections.length!=0&&t454_clickedSectionId==null&&t454_sections[t454_sections.length-1].attr("data-offset-top")>(t454_scrollPosition+300)){t454_navLinks.removeClass('t-active');return null}
$(t454_sections).each(function(e){var t454_curSection=$(this),t454_sectionTop=t454_curSection.attr("data-offset-top"),t454_id=t454_curSection.attr('id'),t454_navLink=t454_sectionIdTonavigationLink[t454_id];if(((t454_scrollPosition+300)>=t454_sectionTop)||(t454_sections[0].attr("id")==t454_id&&t454_scrollPosition>=$(document).height()-$(window).height())){if(t454_clickedSectionId==null&&!t454_navLink.hasClass('t-active')){t454_navLinks.removeClass('t-active');t454_navLink.addClass('t-active');t454_valueToReturn=null}else{if(t454_clickedSectionId!=null&&t454_id==t454_clickedSectionId){t454_valueToReturn=null}}
return!1}});return t454_valueToReturn}
function t454_setPath(){}
function t454_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t454_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-80px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t454_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t454_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t454"),burger=el.find(".t454__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t454_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t706_onSuccessCallback(t706_form){$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t754__init(recid){setTimeout(function(){t_prod__init(recid);t754__hoverZoom_init(recid);t754_initPopup(recid);t754__updateLazyLoad(recid);t754__alignButtons_init(recid)},500)}
function t754__alignButtons_init(recid){var rec=$('#rec'+recid);if(rec.find('[data-buttons-v-align]')[0]){try{t754__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t754__alignButtons(recid)},200));$('.t754').bind('displayChanged',function(){t754__alignButtons(recid)});if($isMobile){$(window).on('orientationchange',function(){t754__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t754__alignButtons(recid){var rec=$('#rec'+recid);var wrappers=rec.find('.t754__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t754__container_mobile-flex')[0]?!0:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t754 .mobile-two-columns')[0]?!0:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];$.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
$.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t754__hoverZoom_init(recid){if(isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid,".t-slds__container")},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t754__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t754__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){t_lazyload_update()},500))}}
function t754_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_sldsInit(recid+' #t754__product-'+lid_prod+'')});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();t754_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0&&curUrl.indexOf('#%21%2Ftproduct%2F')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t754_updateSlider(recid+' #t754__product-'+lid_prod+'');if(window.lazy=='y'){t_lazyload_update()}});if($('#record'+recid).length==0){t754_checkUrl(recid)}
t754_copyTypography(recid)}
function t754_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/');if(tprodIndex<0){tprodIndex=curUrl.indexOf('#%21%2Ftproduct%2F')}}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t754_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t754_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy=='y'){t_lazyload_update()}},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t754_closePopup()}});el.find('.t-popup__close, .t754__close-text').click(function(e){t754_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t754_closePopup()}})}
function t754_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/');if(indexToRemove<0){indexToRemove=curUrl.indexOf('#%21%2Ftproduct%2F')}}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t754_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t754_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t754__title').attr('style');var descrStyle=rec.find('.t754__descr').attr('style');rec.find('.t-popup .t754__title').attr("style",t754_removeSizeStyles(titleStyle));rec.find('.t-popup .t754__descr, .t-popup .t754__text').attr("style",t754_removeSizeStyles(descrStyle))}